name: Update Redirect

on:
  schedule:
    - cron: '17 * * * *' # Runs every hour at 17 mins past the hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-redirect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run script to update redirect
        run: python update_redirect.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlist redirect to latest video"
          file_pattern: "index.html"
